# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://mhmorta.github.io/
baseurl:
title: Mehrzad Mortzavi
author: Mehrzad Mortzavi
description: Personal blog and resume
avatar: profile.jpg
email: mh.morta@gmail.com
github: mhmorta
# twitter: username
linkedin: mhmorta
# stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
# disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
